export { default as authService, login, loginWithGoogle, checkAuth, refreshAuth, redirectToLogin, logout, toSessionData } from './authService'
export type { AuthUser, LoginResult } from './authService'
export { AUTH_BASE_URL, MAIN_SITE_URL, APP_BASE_URL, API_BASE_URL, getLoginUrl, getRegistrationUrl, getLogoutUrl, getAuthMeUrl, getRefreshUrl } from './config'
export { authFetch } from './httpClient'
export { parseCookies, getCookie, getAuthFromCookies, isAuthenticatedViaCookies, clearAuthCookies } from './cookies'
